bump omarchy to v3.2.2

diff --git a/zsh/patches/aliases.patch b/zsh/patches/aliases.patch
--- a/zsh/patches/aliases.patch
+++ b/zsh/patches/aliases.patch
@@ -6,36 +6,43 @@ Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
 <+>UTF-8
 ===================================================================
 diff --git a/default/bash/aliases b/default/bash/aliases
---- a/default/bash/aliases	(revision 1e859d37cb7fef6ac687442dc1fe515d01d1302d)
-+++ b/default/bash/aliases	(date 1759611144120)
-@@ -1,19 +1,6 @@
+--- a/default/bash/aliases	(revision 8a37f3dce71b0764e3758cb86478c503a4a8746e)
++++ b/default/bash/aliases	(date 1764960417170)
+@@ -1,26 +1,6 @@
  # File system
--alias ls='eza -lh --group-directories-first --icons=auto'
--alias lsa='ls -a'
--alias lt='eza --tree --level=2 --long --icons --git'
--alias lta='lt -a'
+-if command -v eza &> /dev/null; then
+-  alias ls='eza -lh --group-directories-first --icons=auto'
+-  alias lsa='ls -a'
+-  alias lt='eza --tree --level=2 --long --icons --git'
+-  alias lta='lt -a'
+-fi
+-
  alias ff="fzf --preview 'bat --style=numbers --color=always {}'"
--alias cd="zd"
--zd() {
--  if [ $# -eq 0 ]; then
--    builtin cd ~ && return
--  elif [ -d "$1" ]; then
--    builtin cd "$1"
--  else
--    z "$@" && printf "\U000F17A9 " && pwd || echo "Error: Directory not found"
--  fi
--}
+-
+-if command -v zoxide &> /dev/null; then
+-  alias cd="zd"
+-  zd() {
+-    if [ $# -eq 0 ]; then
+-      builtin cd ~ && return
+-    elif [ -d "$1" ]; then
+-      builtin cd "$1"
+-    else
+-      z "$@" && printf "\U000F17A9 " && pwd || echo "Error: Directory not found"
+-    fi
+-  }
+-fi
+-
 +alias cd="z"
  open() {
    xdg-open "$@" >/dev/null 2>&1 &
  }
-@@ -25,11 +12,13 @@
- 
+@@ -32,11 +12,13 @@
+
  # Tools
  alias d='docker'
 -alias r='rails'
  n() { if [ "$#" -eq 0 ]; then nvim .; else nvim "$@"; fi; }
- 
+
  # Git
  alias g='git'
 -alias gcm='git commit -m'
